### PR TITLE
fix: do not sort indices for  `ProjectionMask::leaves`

### PR DESCRIPTION
**Pull request by wcy-fdu**
The order of indices passed into `ProjectionMask::leaves`  is meaningless, because "repeated or out of order indices will not impact the final mask"(refer to https://docs.rs/crate/parquet/latest/source/src/arrow/mod.rs#179).  Therefore, we don't need to perform an extra sort, which increases the overhead.

### CODE REVIEW

**Comment by wcy-fdu** [comment]
cc @liurenjie1024 @Xuanwo for awareness.

**Comment by sdd** [comment]
@liurenjie1024 or @Xuanwo are you able to re-run the tests on this? I can't explain why the test would fail the way that it has in CI and when I reproduce the change from this PR on `main` locally, the test passes

**Comment by wcy-fdu** [comment]
> cc @wcy-fdu Would you mind to take a look at the ut failure?

Sure, will fix ut outside of work time.

**Comment by wcy-fdu** [comment]
After investigation, I found that although [ProjectionMask::leaves()](https://github.com/apache/iceberg-rust/blob/2f3554b30a05028aef1d46d37209e24e1ed96582/crates/iceberg/src/arrow/reader.rs#L389) does not require column_indices to be in order, creating [PredicateConverter](https://github.com/apache/iceberg-rust/blob/2f3554b30a05028aef1d46d37209e24e1ed96582/crates/iceberg/src/arrow/reader.rs#L381) requires it to be in order, so it has to be sorted here anyway. Therefore, it seems unnecessary to remove sort.

**Pull request closed without merging**
