### PR TITLE
feat: expose arrow type <-> iceberg type

### PR DESCRIPTION
**Pull request by xxchan**
Previously we only exposed the schema conversion.

### CODE REVIEW

**Review by Xuanwo — COMMENTED** [review]
Mostly LGTM. Would you like to add some unit tests to cover the new APIs?

**Review by Xuanwo — COMMENTED** [review]
Mostly LGTM. Would you like to add some unit tests to cover the new APIs?

**Comment by xxchan** [comment]
I think the tests are already covered by schema conversion tests, as type conversion is just a sub-feature of schema conversion.

**Comment by Xuanwo** [comment]
> I think the tests are already covered by schema conversion tests, as type conversion is just a sub-feature of schema conversion.

Hi, I understand that the logic might be covered by other parts, but we are adding new public APIs. How about adding unit tests directly for these new APIs?

**Comment by xxchan** [comment]
Ok. Do you think it would be enough to add one or two simple api call
examples, or it should cover all cases like schema test?

**Comment by Xuanwo** [comment]
> Do you think it would be enough to add one or two simple api call examples

I believe that's enough.

**Review by Xuanwo — APPROVED** [review]
Thank you, really great!

**Pull request merged**
