### PR TITLE
chord:  Add IssueNavigationLink for RustRover

### PR DESCRIPTION
**Pull request by stream2000**
Add IssueNavigationLink for RustRover

### CODE REVIEW

**Comment by liurenjie1024** [comment]
Sorry, I'm not sure if adding an IDE specific configuration is a good choice. cc @Xuanwo @ZENOTME @Fokko WDYT?

**Comment by stream2000** [comment]
> Sorry, I'm not sure if adding an IDE specific configuration is a good choice. cc @Xuanwo @ZENOTME @Fokko WDYT?

@liurenjie1024 this is just a minor improvement aimed at enhancing the workflow for devs using JetBrains IDEs.  It really helps me in Apache Hudi project, so I port it here.

**Review by liurenjie1024 — APPROVED** [review]
LGTM, thanks!

**Review by Xuanwo — COMMENTED** [review]
I'm not fond of adding `.idea` to git, but I understand that people want a better experience in the IDE.

Maybe we can add this ignore in the `.idea` folder

https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore

**Comment by stream2000** [comment]
> https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
```shell
.idea/*
!.idea/vcs.xml
```
I think excluding `.idea/vcs.xml` in this way should be enough.

**Comment by Xuanwo** [comment]
> I think excluding `.idea/vcs.xml` in this way should be enough.

Ok, but I prefer put it in `.idea/.gitignore`.

**Comment by stream2000** [comment]
> Ok, but I prefer put it in `.idea/.gitignore`.

Sure and done, thanks for your review~

**Review by Fokko — APPROVED** [review]
I'm typically also a bit reluctant to add IDEA-specific things to the repository. But there seems to be a consensus of adding it. Thanks @stream2000 for working on this! 🙌

**Pull request merged**
