### PR TITLE
docs: Upload crates

### PR DESCRIPTION
**Pull request by Fokko**
I noticed this section was missing

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Thanks! By the way, we can use CI to test and publish the crates while pushing tag like https://github.com/apache/opendal/blob/main/.github/workflows/release_rust.yml.

I'm willing to do this if you like it.

**Comment by Fokko** [comment]
@Xuanwo Great suggestion, I think that would be even easier and less error-prone 👍

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Comment by liurenjie1024** [comment]
> Thanks! By the way, we can use CI to test and publish the crates while pushing tag like https://github.com/apache/opendal/blob/main/.github/workflows/release_rust.yml.
> 
> I'm willing to do this if you like it.

LGTM! Is it possible to include other stuff like uploading tars in svn?

**Comment by Xuanwo** [comment]
> Is it possible to include other stuff like uploading tars in svn?

This task involves the password for PMC's ASF account. It's best to avoid it.

**Comment by Fokko** [comment]
We can close this in favor of the GH Action :)

**Pull request closed without merging**
