### PR TITLE
ci: Fix CI for bindings python

### PR DESCRIPTION
**Pull request by Xuanwo**

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Review by sungwy — APPROVED** [review]
@Xuanwo does this mean we would have to find a different approach to address the issue attempted to be resolved in https://github.com/apache/iceberg-rust/pull/666 ?

**Review by kevinjqliu — APPROVED** [review]
Looks like a revert of #666. CI looks good now https://github.com/apache/iceberg-rust/commits/main/ 

Will this break CI again?

**Comment by Xuanwo** [comment]
Hi, @kevinjqliu @sungwy, thank you for the review!

Github fix this from the runner side: https://github.com/actions/runner-images/pull/10794

I believe we can continue to use pip in the current manner.

**Comment by kevinjqliu** [comment]
FYI, CI failing on main
https://github.com/apache/iceberg-rust/commits/main/

Is it related to this PR? 

error message,
```
error: use of deprecated method `opendal::Operator::is_exist`: rename to `exists` for consistence with `std::fs::exists`
   --> crates/iceberg/src/io/file_io.rs:100:15
    |
100 |         Ok(op.is_exist(relative_path).await?)
    |               ^^^^^^^^
    |
    = note: `-D deprecated` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(deprecated)]`

error: use of deprecated method `opendal::Operator::is_exist`: rename to `exists` for consistence with `std::fs::exists`
   --> crates/iceberg/src/io/file_io.rs:246:14
    |
246 |             .is_exist(&self.path[self.relative_path_pos..])
    |              ^^^^^^^^

error: use of deprecated method `opendal::Operator::is_exist`: rename to `exists` for consistence with `std::fs::exists`
   --> crates/iceberg/src/io/file_io.rs:328:14
    |
328 |             .is_exist(&self.path[self.relative_path_pos..])
    |              ^^^^^^^^
```

**Comment by Xuanwo** [comment]
> FYI, CI failing on main
> 
> https://github.com/apache/iceberg-rust/commits/main/
> 
> 
> 
> Is it related to this PR? 
> 
> 
> 
> error message,
> 
> ```
> 
> error: use of deprecated method `opendal::Operator::is_exist`: rename to `exists` for consistence with `std::fs::exists`
> 
>    --> crates/iceberg/src/io/file_io.rs:100:15
> 
>     |
> 
> 100 |         Ok(op.is_exist(relative_path).await?)
> 
>     |               ^^^^^^^^
> 
>     |
> 
>     = note: `-D deprecated` implied by `-D warnings`
> 
>     = help: to override `-D warnings` add `#[allow(deprecated)]`
> 
> 
> 
> error: use of deprecated method `opendal::Operator::is_exist`: rename to `exists` for consistence with `std::fs::exists`
> 
>    --> crates/iceberg/src/io/file_io.rs:246:14
> 
>     |
> 
> 246 |             .is_exist(&self.path[self.relative_path_pos..])
> 
>     |              ^^^^^^^^
> 
> 
> 
> error: use of deprecated method `opendal::Operator::is_exist`: rename to `exists` for consistence with `std::fs::exists`
> 
>    --> crates/iceberg/src/io/file_io.rs:328:14
> 
>     |
> 
> 328 |             .is_exist(&self.path[self.relative_path_pos..])
> 
>     |              ^^^^^^^^
> 
> ```

Not related. opendal released a new version. I will fix it.

**Pull request merged**
