### PR TITLE
WIP: Use localhost instead of container hostname

### PR DESCRIPTION
**Pull request by Fokko**
These changes allow me to also run the tests locally. 

Closes https://github.com/apache/iceberg-rust/issues/719

### CODE REVIEW

**Comment by Fokko** [comment]
@liurenjie1024 unfortunately yes, the `172.*` IPs that the library return don't work on my end.

**Comment by Fokko** [comment]
@liurenjie1024 Ah, yes, that would be one of the drawbacks

@nastra Asking for a favor. Could you clone this repository, and try to run `make test`? I wanted to check if I'm the only one that's in this situation.

**Comment by nastra** [comment]
@Fokko you're not alone. Those tests fail for me too using native Docker on OSX due to networking:

```
test tests::gcs_exists has been running for over 60 seconds
test tests::gcs_read has been running for over 60 seconds
test tests::gcs_write has been running for over 60 seconds
test tests::gcs_read ... FAILED
test tests::gcs_exists ... FAILED
test tests::gcs_write ... FAILED

failures:

---- tests::gcs_read stdout ----
thread 'tests::gcs_read' panicked at crates/iceberg/tests/file_io_gcs_test.rs:67:14:
called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.20.0.2:4443/storage/v1/b)

Caused by:
    0: client error (Connect)
    1: tcp connect error: Operation timed out (os error 60)
    2: Operation timed out (os error 60)

---- tests::gcs_exists stdout ----
thread 'tests::gcs_exists' panicked at crates/iceberg/tests/file_io_gcs_test.rs:67:14:
called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.20.0.2:4443/storage/v1/b)

Caused by:
    0: client error (Connect)
    1: tcp connect error: Operation timed out (os error 60)
    2: Operation timed out (os error 60)

---- tests::gcs_write stdout ----
thread 'tests::gcs_write' panicked at crates/iceberg/tests/file_io_gcs_test.rs:67:14:
called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.20.0.2:4443/storage/v1/b)

Caused by:
    0: client error (Connect)
    1: tcp connect error: Operation timed out (os error 60)
    2: Operation timed out (os error 60)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::gcs_exists
    tests::gcs_read
    tests::gcs_write

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 75.03s
```

**Comment by Fokko** [comment]
I've switched to Orbstack and it works pretty well :)

**Pull request closed without merging**
