### PR TITLE
chore: Bump to version 0.3.0

### PR DESCRIPTION
**Pull request by Fokko**

### CODE REVIEW

**Review by liurenjie1024 — APPROVED** [review]
LGTM, I think it's fine to upgrade it now.

**Comment by Xuanwo** [comment]
> LGTM, I think it's fine to upgrade it now.

Ok, so we will always bump to next version during release?

**Comment by Xuanwo** [comment]
The difference lies in how we determine the version to release.

Previously, we would decide on the version just before releasing it. This involved starting a discussion on the mailing list and then bumping up the version accordingly. However, now we must bump the version immediately without prior knowledge of what changes this release will include. For instance, should we release `0.3.0` even if there haven't been any breaking changes?

**Comment by liurenjie1024** [comment]
> The difference lies in how we determine the version to release.
> 
> Previously, we would decide on the version just before releasing it. This involved starting a discussion on the mailing list and then bumping up the version accordingly. However, now we must bump the version immediately without prior knowledge of what changes this release will include. For instance, should we release `0.3.0` even if there haven't been any breaking changes?

I think in semver's semantics, upgrading different part has different meanings:

1. Upgrading major version means breaking change. For example, we can upgrade it to 1 when we have finished feature parity with java api, and upgrade it when we have breaking changes.
2. Upgrading minor version means add new features without breaking change, e.g. `0.2.0` -> `0.3.0`. Since we are currently adding features in main branch, so I think it's fine to upgrade minor version in main branch.
3. Upgrading patch version means adding bug fix without new feature, e.g. `0.2.0` -> `0.2.1`. In this case, we should create a 0.2.x branch for tags/0.2.0, and adding both bug fix pr to both main branch and 0.2.x, and create tags from 0.2.x branch for patch version.

**Comment by Fokko** [comment]
What we do at Python/Java, is create a branch for each major/minor version. If there are any bugs then we can backport them to the branch, and do a quick release. This way you don't have to keep track if you merge any new functionality to the main branch (because patch releases should only contain fixes).

**Comment by Xuanwo** [comment]
Most rust packages just keep moving on next version and don't do backport and cherrypick. And considering our current state, it's less likely for us to maintaining a v0.2 branch 🫣

**Comment by liurenjie1024** [comment]
> What we do at Python/Java, is create a branch for each major/minor version. If there are any bugs then we can backport them to the branch, and do a quick release. This way you don't have to keep track if you merge any new functionality to the main branch (because patch releases should only contain fixes).

+1, we could do this when this library gets mature enough, we don't need this since it's in a relative early stage.

**Comment by liurenjie1024** [comment]
cc @Xuanwo Any other concerns?

**Comment by Xuanwo** [comment]
> cc @Xuanwo Any other concerns?

I'm ok with this PR content but not its timing.

As I mentioned before, we can decide the version to release in the discussion and bump version in a separate PR to initiate the release process.

**Comment by liurenjie1024** [comment]
> As I mentioned before, we can decide the version to release in the discussion and bump version in a separate PR to initiate the release process.

Sounds reasonable to me.

**Comment by Fokko** [comment]
I'll close this for now. In Java/Python world it is typical to bump the version after the release. Maybe we should create consensus on bumping versions first.

**Pull request closed without merging**
