### PR TITLE
Follow naming convention from Iceberg's Java and Python implementations

### PR DESCRIPTION
**Pull request by s-akhtar-baig**
Issues: https://github.com/apache/iceberg-rust/issues/145

Description: Rename ManifestListEntry as ManifestFile to follow Iceberg Spec and naming convention of Iceberg's Java and Python implementations.

### CODE REVIEW

**Comment by s-akhtar-baig** [comment]
@liurenjie1024, I have refactored the code. Please take a look when you get a chance. Thanks!

**Review by liurenjie1024 — APPROVED** [review]
LGTM, thanks!

**Comment by s-akhtar-baig** [comment]
Thanks @liurenjie1024! I think I would also need Fokko's review to get these merged, right?

@Fokko, can you please review these changes? Thanks in advance!

**Comment by liurenjie1024** [comment]
> I think I would also need Fokko's review to get these merged, right?

Yes.

**Review by Xuanwo — COMMENTED** [review]
Thanks!

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Review by Fokko — APPROVED** [review]
Thanks for working on this @s-akhtar-baig! 🙌 I think aligning the naming, makes it much easier for people to work across languages. Thanks @liurenjie1024 and @Xuanwo for the review.

**Pull request merged**
