### PR TITLE
refactor: Replace unwrap

### LINKED ISSUE #177: Remove `unwrap()` in `ManifestListWriter.close()`
`unwrap()` should not be used in normal code, but `ManifestListWriter.close()` uses it.
It should be removed and the error should be properly handled like `ManifestWriter.write()`.

### PR DESCRIPTION
**Pull request by odysa**
Resolve #177

Replace `unwrap` with `?` and `expect`.

### CODE REVIEW

**Review by liurenjie1024 — APPROVED** [review]
LGTM, thanks!

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Review by Fokko — APPROVED** [review]
Thanks for raising this PR @odysa, and @liurenjie1024 @Xuanwo for the review! 🙌

**Comment by zeodtr** [comment]
@odysa @liurenjie1024 @Xuanwo @Fokko Please see my comment: https://github.com/apache/iceberg-rust/issues/177#issuecomment-1924916131
Thank you.

**Pull request merged**
