### PR TITLE
fix: chrono dep

### PR DESCRIPTION
**Pull request by odysa**
#234 used `TimeDelta`
`TimeDelta` was first introduced in [v0.4.34](https://github.com/chronotope/chrono/releases/tag/v0.4.34).

### CODE REVIEW

**Comment by liurenjie1024** [comment]
Hi, @odysa Thanks for this pr. I think this could be solved by `cargo update`? As a library, it's usually not good practice to fix it to a minor version.

**Comment by liurenjie1024** [comment]
cc @odysa Should we close this?

**Comment by Xuanwo** [comment]
> I think this could be solved by `cargo update`?

This is required to make sure our users depends on `>= 0.4.34` since old versions don't have this new type.

**Comment by liurenjie1024** [comment]
> > I think this could be solved by `cargo update`?
> 
> 
> 
> This is required to make sure our users depends on `>= 0.4.34` since old versions don't have this new type.

Cool, I think we can upgrade to 0.5 when new version is released.

**Review by liurenjie1024 — APPROVED** [review]
Thanks @odysa

**Pull request merged**
