### PR TITLE
Set `ghp_{pages,path}` properties

### LINKED ISSUE #137: doc: rust.iceberg.apache.org is not resolved
`rust.iceberg.apache.org` is not resolved, do we need to submit a ticket to infra?

```shell
:) drill rust.iceberg.apache.org
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 27319
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; rust.iceberg.apache.org.     IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
apache.org.     598     IN      SOA     ns-558.awsdns-05.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Tue Dec 26 19:59:10 2023
;; MSG SIZE  rcvd: 125
```

cc @Fokko @bitsondatadev

### PR DESCRIPTION
**Pull request by Fokko**
In the ASF yaml. I don't think we should make it a protected branch because I think they overwrite it every time with a force push.

Resolves #137 hopefully!

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Comment by Xuanwo** [comment]
The same setup works on [opendal](https://github.com/apache/incubator-opendal/blob/main/.asf.yaml), I'm not sure why it doesn't work there.

**Review by liurenjie1024 — APPROVED** [review]
Thanks!

**Comment by Fokko** [comment]
@Xuanwo Probably Github Pages had been enabled through an infra ticket in the past. The `.asf.yaml` is not declarative, if you leave anything out it will not disable it, you need to do that explicitly.

**Comment by Xuanwo** [comment]
> @Xuanwo Probably Github Pages had been enabled through an infra ticket in the past. The `.asf.yaml` is not declarative, if you leave anything out it will not disable it, you need to do that explicitly.

That makes sense!

**Review by amogh-jahagirdar — APPROVED** [review]
Thanks @Fokko , thanks for reviews @Xuanwo @liurenjie1024 !

**Pull request merged**
