### PR TITLE
feat: Bump version 0.2.0 to prepare for release.

### PR DESCRIPTION
**Pull request by liurenjie1024**
We have reached consensus to run the first release: `0.2.0`, see [the discussion](https://lists.apache.org/thread/8sj66kf02qd0qtyyrj4gox3yozjk3vtd) in mail list. 

This is the first step of #180 :

1. Bump version to 0.2.0
2. Update dependencies.

### CODE REVIEW

**Comment by liurenjie1024** [comment]
cc @ZENOTME @Xuanwo @Fokko PTAL

**Review by Xuanwo — APPROVED** [review]
Let's rock!

**Comment by Xuanwo** [comment]
I believe we need to wait for https://github.com/apache/iceberg-rust/pull/174

**Comment by Fokko** [comment]
@liurenjie1024 Now #174 has been merged, can you regenerate the dependencies tsv's?

**Comment by liurenjie1024** [comment]
> @liurenjie1024 Now #174 has been merged, can you regenerate the dependencies tsv's?

Yeah, let's move!

**Review by Fokko — APPROVED** [review]

**Comment by manuzhang** [comment]
It would be better not to bump release version on main branch. All following commits (snapshot version) will carry this release version.

**Comment by Xuanwo** [comment]
> It would be better not to bump release version on main branch. All following commits (snapshot version) will carry this release version.

It's okay for the rust ecosystem that we don't releases snapshots. We also want users who rely on git versions to start using the new version.

**Pull request merged**
