### PR TITLE
refactor: Move puffin crate contents inside iceberg crate

### PR DESCRIPTION
**Pull request by fqaiser94**
Part of https://github.com/apache/iceberg-rust/issues/744

# Summary
- Move contents of the puffin crate over to the existing iceberg crate
- Delete the puffin crate

# Context
@liurenjie1024 [raised a good question about why we needed a separate puffin crate at all.](https://github.com/apache/iceberg-rust/pull/745#discussion_r1881794442) 
On reflection, I realized that there's no particularly strong reason to have a separate puffin crate. 
Hence this PR.

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
A concern is whether all Iceberg users will require Puffin support. It's important to note that users who only access the catalog will also need to pull the Iceberg core. However, I don't have a strong opinion on this.

I'll approve this to unblock the PR from merging. This decision can be left to @Fokko and @liurenjie1024.

**Comment by Fokko** [comment]
I can see value in both. It could be that folks just want to have logic to read the Puffin files, and then they could just use the crate (for example PyIceberg) without having to pull in core.

**Comment by Xuanwo** [comment]
Thank you, @Fokko, for the feedback. Since neither of us has a strong opinion on this and the suggestion comes from @liurenjie1024 with agreement from @fqaiser94, I believe there’s no need to wait for another round of review. This change can easily be reverted at any time if we find it to be incorrect. So, let’s move forward.

**Comment by Fokko** [comment]
That makes sense @liurenjie1024 thanks for the explanation 👍  Coming from Java/Python, everything in Rust is small anyway, so I think we're good by moving Puffin into Core.

**Pull request merged**
