### PR TITLE
chore: Add licenses for markdown files

### PR DESCRIPTION
**Pull request by Xuanwo**
Fix https://github.com/apache/iceberg-rust/issues/10

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @Fokko, maybe you will be willing to help review this PR?

**Comment by nastra** [comment]
Given that we're updating a bunch of files, should this maybe done as part of https://github.com/apache/iceberg-rust/pull/7?

**Comment by Xuanwo** [comment]
> Given that we're updating a bunch of files, should this maybe done as part of #7?

LGTM.

**Comment by Xuanwo** [comment]
Included in https://github.com/apache/iceberg-rust/pull/7

**Pull request closed without merging**
