### PR TITLE
chore: Change iceberg into workspace

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR will change iceberg into workspace. I feel like it's better to split iceberg features into different crates so that we can work (and release) concurrently instead of waiting for the release of a whole iceberg.

For example, we can add iceberg rest api client first which could be generated from OpenAPI Specs and less related to iceberg core itself.

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @Fokko, @JanKaul, @liurenjie1024 & @ZENOTME to take a look. Thanks.

**Comment by Xuanwo** [comment]
The problem is the release process.

- Can we release `iceberg-rest-catalog-client` seperately?
- Is it a heavy work?

Need more input from @Fokko.

**Comment by Xuanwo** [comment]
> I think it's better to make it part of core crate?

Both LGTM. My motivation is to release it sooner, allowing us to involve more users and developers in our project.

**Comment by Fokko** [comment]
Releasing takes some effort, but if everything is well automated, and there are folks around to test and validate the release, then it is a quick process. Even if it is not a lot of effort, it takes 3 days because everyone needs to be able to chime in and test the release. It would be great to set up a how-to-release guide, examples for [Java](https://iceberg.apache.org/how-to-release/) and [Python](https://py.iceberg.apache.org/how-to-release/) can be used for inspiration :)

What I think would be easiest, but correct me if I'm wrong here. Just release all the crates every time with the same version, so the versions of the crates don't diverge. WDYT?

**Comment by Xuanwo** [comment]
> Just release all the crates every time with the same version, so the versions of the crates don't diverge. WDYT?

I'm not sure about that. Maybe we can release `iceberg-rest-catalog-client` with `0.0.1` and `iceberg` with `0.2.0`?

If we are going to release everything in the same version, it's better to put them in the same crate with diffent feature flag instead.

> NOTE: feature flag in rust is similiar to `pip install package[addon]`.

**Comment by JanKaul** [comment]
I'm definitely in favor of small crates compared to using features. From my perspective features can get really messy when there is a hierarchy of crates depending on each other (Crate A uses feature 1 of `iceberg` and crate B wants to use crate A without feature 1 and so on). Plus compile times should be much better.

There is one downside. You cannot implement traits for structs defined outside of your crate. So if you want to implement Datafusions `TableProvider` for example, you have to create a wrapper struct like so:

```
struct DatafusionTable(IcebergTable);
```

Reagrding the release cadence, I have no preference. We could release the small crates all with the same version number or release them separately.

**Review by JanKaul — APPROVED** [review]
LGTM, Thank you.

**Pull request merged**
