### PR TITLE
Add workflow for cargo audit

### PR DESCRIPTION
**Pull request by sdd**
Resolves https://github.com/apache/iceberg-rust/issues/209.

Workflow file copied directly from https://github.com/apache/arrow-datafusion/blob/main/.github/workflows/audit.yml

### CODE REVIEW

**Review by liurenjie1024 — APPROVED** [review]
LGTM, thanks!

**Comment by liurenjie1024** [comment]
cc @Fokko @Xuanwo PTAL

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Review by Fokko — APPROVED** [review]
Nice! I saw that Avro rust has it also as a CI. Thanks for working on this @sdd! @Xuanwo and @liurenjie1024 thanks for the review! 👍

**Pull request merged**
