### PR TITLE
[WIP] feat: basic implementation of dynamodb catalog

### PR DESCRIPTION
**Pull request by odysa**
todo
* [ ] Implement list namespaces
* [ ] Use environment variables for configs.
* [ ] unit tests
* [ ] integration tests

### CODE REVIEW

**Comment by Xuanwo** [comment]
There's a discussion about `Deprecate DynamodbCatalog` on dev@i.a.o. Maybe we should join in?

LINK: https://lists.apache.org/thread/b92zwcvy7917bhr5t00b07f7r8qqwxqj

**Comment by Xuanwo** [comment]
Based on the discussion, it appears that few people utilize this catalog. Do you have a specific use case for it?

**Comment by odysa** [comment]
They suggest to use Glue. Let me figure out does it work for me. cc @Xuanwo

**Comment by Xuanwo** [comment]
> They suggest to use Glue. Let me figure out does it work for me. cc @Xuanwo

Thanks! Feel free to implement the DynamoDB catalog in iceberg-rust. I just wanted to update you on the current situation within the community: there is a disscusion to deprecate it. And it's highly possible for us to deprecate it too someday.

**Comment by odysa** [comment]
Update: We decide to use Postgres, cuz none of us know Glue😢. I will start working on the SQL Catalog which I think it may be more widely used.
I will close this PR and move this implementation to my personal repo.

**Comment by liurenjie1024** [comment]
> Update: We decide to use Postgres, cuz none of us know Glue😢. I will start working on the SQL Catalog which I think it may be more widely used. I will close this PR and move this implementation to my personal repo.

I remember @JanKaul mentioned that he already has an implementation for this, maybe we can help to port it?

**Comment by JanKaul** [comment]
Yes, sorry I didn't have time to implement it. I'll try to work on it today.

**Pull request closed without merging**
