### PR TITLE
ci: add rust-cache action

### PR DESCRIPTION
**Pull request by xxchan**
alternative to https://github.com/apache/iceberg-rust/pull/824

### CODE REVIEW

**Comment by xxchan** [comment]
image

It performs much better than sccache (https://github.com/apache/iceberg-rust/pull/824#issuecomment-2551668279)

cc @liurenjie1024 @Fokko @Xuanwo @kevinjqliu

**Comment by Xuanwo** [comment]
Hi, as mentioned in https://github.com/apache/iceberg-rust/pull/849#issuecomment-2562904637, I'm fine with checking in `Cargo.lock`. Would you like to split this PR into two? One for checking in the lock file and the other for adding rust-cache.

I apologize for this request since the change is really small. However, I genuinely want to make the history clearer and more readable.

**Comment by xxchan** [comment]
Done: #851

**Review by Xuanwo — APPROVED** [review]
Thank you @xxchan for building this, let's move.

**Pull request merged**
