### PR TITLE
feat: add `DataFileWriter` tests for schema and partition

### LINKED ISSUE #726: Extend the `DataFileWriterBuilder` tests
In `data_file_writer` we write out a schema but don't have any tests for that. I think it would be good to write out a schema to validate that the field-IDs are there (they are, I checked by hand).

### PR DESCRIPTION
**Pull request by jonathanc-n**
Closes #726

Added `DataFileWriter` tests for schema and partition

### CODE REVIEW

**Review by Fokko — DISMISSED** [review]
This looks good, thanks @jonathanc-n for adding this 👍

**Comment by Fokko** [comment]
@jonathanc-n Could you rebase the PR? I'll merge it right away after that 👍

**Comment by jonathanc-n** [comment]
@Fokko Sorry for the wait, was on a break. Merge errors should be fixed!

**Review by Xuanwo — APPROVED** [review]
Thank you @jonathanc-n for working on this and @Fokko's review. Let's move!

**Pull request merged**
